export const colors = {
  background: "#b0ddd1",
  border: "#377f7c",
  profileText: "#285B59",
  title: "#006e73",
  buttonText: "green",
  inputText: "grey",
  cardBackgroud: "white",
  cardBack: "#00a6ae",
  cardIcon: "#c1e5db",
  white: "white",
  black: "black",
  cardShadow: "#000",
  lightBlue: "#d4ebf2",
  grey: "#a8a8a8",
};
