export const colors = {
  background: "#b0ddd1",
  border: "#377f7c",
  title: "#006e73",
  button: "white",
  buttonPressed: "#a6a6ed",
  buttonText: "#377f7c",
  inputText: "grey",
  cardBackgroud: "white",
  cardBack: "#00a6ae",
  cardIcon: "#c1e5db",
  white: "white",
  black: "black",
  cardShadow: '#000',
};
